apiVersion: v1
kind: Pod
metadata:
  name: api-medic-login-pod
  labels:
    app: api-medic-login
spec:
  containers:
  - name: api-medic-login
    image: leo1897/medic-login
    ports:
    - containerPort: 8000
    command: ["/bin/bash","-c"]
    args: ["python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    env:
    - name: DATABASE_NAME
      value: medic-bd
    - name: DATABASE_USER
      value: leonardo
    - name: DATABASE_HOST
      value: db-test-free.cdxsrhofpryf.us-east-1.rds.amazonaws.com
    - name: DATABASE_PASS
      value: testeo