apiVersion: v1
kind: Pod
metadata:
  name: api-medic-pacientes-pod
  labels:
    app: api-medic-pacientes
spec:
  containers:
  - name: api-medic-pacientes
    image: leo1897/medic-pacientes
    ports:
    - containerPort: 7000
    command: ["/bin/bash","-c"]
    args: ["python manage.py migrate && python manage.py runserver 0.0.0.0:7000"]
    env:
    - name: DATABASE_NAME
      value: medic-bd
    - name: DATABASE_USER
      value: leonardo
    - name: DATABASE_HOST
      value: AWS-RDS-postgresql
    - name: DATABASE_PASS
      value: testeo