apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
  labels:
    app: front-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: medic-frontend
        image: leo1897/medic-front
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_IP
          value: 'http://172.17.0.2'
        - name: JWT_BACKEND_IP
          value: '172.17.0.2'

