apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-login
  template:
    metadata:
      labels:
        app: api-login
    spec:
      containers:
      - name: api-medic-login
        image: leo1897/medic-login
        ports:
        - containerPort: 8000
        command: ["/bin/bash","-c"]
        args: ["python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
        env:
        - name: DATABASE_NAME
          value: medic-bd
        - name: DATABASE_USER
          value: leonardo
        - name: DATABASE_HOST
          value: aws-rds-postgresql
        - name: DATABASE_PASS
          value: testeo
        - name: K8S_CLUSTER_IP
          value: 192.168.99.100

