apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deploy
  labels:
    app: login-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-login
  template:
    metadata:
      labels:
        app: api-login
    spec:
      containers:
      - name: medic-login
        image: leo1897/medic-login
        ports:
        - containerPort: 8000
        command: ["/bin/bash","-c"]
        args: ["python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
        env:
        - name: DATABASE_NAME
          value: dda5h4s6dsde1
        - name: DATABASE_USER
          value: zjrbxymjtnzmbr
        - name: DATABASE_HOST
          value: user-db
        - name: DATABASE_PASS
          value: 1c8e38a949ec11bf83ac27543ca0028eca59b2d6d67ffdc93885d5168495e4eb
        - name: ALLOWED_HOST
          value: '*'
        - name: CORS_ALLOWED_IP
          value: 'http://anydomain.com'
        - name: CORS_ALLOWED_ALL
          value: 'true'



