apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacientes-deploy
  labels:
    app: pacientes-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pacientes
  template:
    metadata:
      labels:
        app: api-pacientes
    spec:
      containers:
      - name: medic-pacientes
        image: leo1897/medic-pacientes
        ports:
        - containerPort: 7000
        command: ["/bin/bash","-c"]
        args: ["python manage.py migrate && python manage.py runserver 0.0.0.0:7000"]
        env:
        - name: DATABASE_NAME
          value: medic-bd
        - name: DATABASE_USER
          value: leonardo
        - name: DATABASE_HOST
          value: pacientes-db
        - name: DATABASE_PASS
          value: testeo
        - name: ALLOWED_HOST
          value: '*'
        - name: CORS_ALLOWED_IP
          value: 'http://anydomain.com'
        - name: CORS_ALLOWED_ALL
          value: 'true'
