apiVersion: v1
kind: Service
metadata:
  name: np-login
  labels:
    app: np-login
spec:
  type: NodePort
  ports:
  - nodePort: 31666
    port: 8000
    targetPort: 8000
  selector:
    app: api-login