apiVersion: v1
kind: Service
metadata:
  name: np-pacientes
  labels:
    app: np-pacientes
spec:
  type: NodePort
  ports:
  - nodePort: 31777
    port: 7000
    targetPort: 7000
  selector:
    app: api-pacientes